# Party members
# status = leader | in_party | joining | invitable

[member.0]
gamertag=Twister
status=leader
activity=In party chat
talking=1
muted=0

[member.1]
gamertag=MajorNelson
status=in_party
activity=Playing Gears of War 2
talking=0
muted=0

[member.2]
gamertag=LarryHryb
status=in_party
activity=In party chat
talking=1
muted=0

[member.3]
gamertag=Rareware
status=joining
activity=Connecting...
talking=0
muted=0

[member.4]
gamertag=Bungie
status=invitable
activity=Online
talking=0
muted=0
